version: '3.4'

services:
  Mizekar.Micro.Idea:
    image: ${DOCKER_REGISTRY}Mizekar.Micro.Idea
    build:
      context: .
      dockerfile: Mizekar.Micro.Idea\Dockerfile      
    depends_on:
      - db
  db:
    image: microsoft/mssql-server-windows-express
    environment:
            SA_PASSWORD: MyStrong_*123456
            ACCEPT_EULA: "Y"
